name = "UI Custom"
license = "MIT"
licenselink = "https://github.com/site-0001/ui-custom/blob/main/LICENSE"
description = "WebSite User Interface"
homepage = "https://kitsunesolar.com"
tags = ["website", "responsive", "multilingual", "mobile"]
features = ["posts", "shortcodes", "comments"]
min_version = "0.82.0"

[author]
  name = "Kitsune Solar"
  homepage = "https://kitsunesolar.com"
